import {labels,number,budget,powerAt,noise,convertPower,doppler,validPlan} from './calculations.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=2)=>x==null||!Number.isFinite(x)?'Out of range':(x!==0&&(Math.abs(x)<.001||Math.abs(x)>=1e9)?x.toExponential(6):x.toLocaleString('en-US',{maximumFractionDigits:d}));
let timer;function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('notice').hidden=true,5500);}
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function write(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true;}catch{notice('Unable to save: browser storage is full or unavailable.');return false;}}
const names=['Frequency','Distance','TX power','TX antenna gain','RX antenna gain','RX amplifier gain','TX cable loss','RX cable loss','Receiver sensitivity','Required margin'];
const units=['MHz','km','dBm','dBi','dBi','dB','dB','dB','dBm','dB'],defaults=['','','','','','0','0','0','','0'],placeholder=['2.4','1','20','2','2','0','0','0','-90','10'];
function field(id,title,value,unit='',extra=''){return `<label for="${id}">${title}<div class="input-unit"><input id="${id}" inputmode="decimal" value="${esc(value)}" ${extra}>${unit?`<span>${unit}</span>`:''}</div></label>`;}
for(let i=0;i<10;i++){const parent=i<2?'propagation':i<5?'antenna':i<8?'losses':'requirements';$(parent).insertAdjacentHTML('beforeend',field('v'+i,names[i],defaults[i],i<2?'':units[i],`placeholder="e.g. ${placeholder[i]}"`));}
$('v0').after(Object.assign(document.createElement('select'),{id:'frequency-unit',ariaLabel:'Frequency unit',innerHTML:'<option value="1000">GHz</option><option value="1">MHz</option>'}));
$('v1').after(Object.assign(document.createElement('select'),{id:'distance-unit',ariaLabel:'Distance unit',innerHTML:'<option value="1">km</option><option value="0.001">m</option>'}));
const saved=read('rf.inputs',{});for(const [id,v] of Object.entries(saved)){if($(id)&&typeof v==='string')$(id).value=v;}
const draftIds=[...Array.from({length:10},(_,i)=>'v'+i),'frequency-unit','distance-unit'];
function persist(){write('rf.inputs',Object.fromEntries(draftIds.map(id=>[id,$(id).value])));}
let snapshot=null,loaded=null,undo=null,plans=read('rf.plans',[]),selected=[];plans=Array.isArray(plans)?plans.filter(validPlan):[];
function tab(id){document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-tab]').forEach(e=>{if(e.dataset.tab===id)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current');});if(id==='plans')renderPlans();}
document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>tab(e.dataset.tab));
function invalidate(){snapshot=null;$('analysis').hidden=true;$('breakdown').hidden=true;$('error').textContent='';$('result').innerHTML='<p class="eyebrow">LINK PERFORMANCE</p><h2>Awaiting calculation</h2><p>Parameters have changed. Press "Calculate Link Budget".</p>';persist();}
for(let i=0;i<10;i++)$('v'+i).addEventListener('input',invalidate);
function bindUnit(selectId,inputId,onChange){const el=$(selectId);let old=number(el.value);el.addEventListener('change',()=>{const value=number($(inputId).value),next=number(el.value);if(Number.isFinite(value)){const converted=value*(old/next);$(inputId).value=Number.isFinite(converted)&&!(value!==0&&converted===0)?String(Number(converted.toPrecision(15))):'';}old=next;onChange();});return ()=>old=number(el.value);}
const resetF=bindUnit('frequency-unit','v0',invalidate),resetD=bindUnit('distance-unit','v1',invalidate);
function values(){return Array.from({length:10},(_,i)=>number($('v'+i).value)*(i===0?number($('frequency-unit').value):i===1?number($('distance-unit').value):1));}
$('budget-form').onsubmit=e=>{e.preventDefault();try{const v=values();budget(v);snapshot={...(loaded??{}),id:crypto.randomUUID(),date:new Date().toISOString(),values:v,name:loaded?.name??'',notes:loaded?.notes??'',bandwidth:loaded?.bandwidth??'1000000',noiseFigure:loaded?.noiseFigure??'3',requiredSNR:loaded?.requiredSNR??'10',measured:loaded?.measured??''};$('error').textContent='';showSnapshot();if($('animation').checked&&!matchMedia('(prefers-reduced-motion: reduce)').matches){$('result').classList.remove('pulse');void $('result').offsetWidth;$('result').classList.add('pulse');}if($('haptics').checked&&navigator.vibrate)navigator.vibrate(30);}catch(err){$('error').textContent=err.message;const i=values().findIndex((v,i)=>!Number.isFinite(v)||(i<2&&v<=0)||([6,7,9].includes(i)&&v<0));if(i>=0){const el=$('v'+i),detail=el.closest('details');if(detail)detail.open=true;el.focus();}}};
$('clear').onclick=()=>{undo={fields:Object.fromEntries(draftIds.map(id=>[id,$(id).value])),loaded};for(let i=0;i<10;i++)$('v'+i).value=defaults[i];loaded=null;invalidate();$('undo').hidden=false;};
$('undo').onclick=()=>{if(!undo)return;for(const [id,v] of Object.entries(undo.fields))$(id).value=v;loaded=undo.loaded;resetF();resetD();undo=null;$('undo').hidden=true;invalidate();};
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function showSnapshot(){const r=budget(snapshot.values);$('result').innerHTML=`<p class="eyebrow">LINK PERFORMANCE</p><p class="status ${r.meets?'':'warn'}">${r.status}</p><p>Link margin</p><div class="big">${fmt(r.margin)} <small>dB</small></div><small>Required margin ${fmt(snapshot.values[9])} dB</small><div class="metrics">${[['Receiver input',r.output,'dBm'],['RX antenna output',r.received,'dBm'],['Free-space loss',r.fspl,'dB'],['Maximum distance',r.maxDistance,'km']].map(([l,v,u])=>`<div><small>${l}</small><strong>${fmt(v)} ${u}</strong></div>`).join('')}</div>`;$('breakdown').hidden=false;$('breakdown').innerHTML='<h3>Seven-Stage Power Breakdown</h3>'+r.stages.map(([n,o,p],i)=>`<div class="stage"><div>${i+1}. ${n}<small>${esc(o)}</small></div><b>${fmt(p)} dBm</b></div>`).join('');$('analysis').hidden=false;$('calculated-at').textContent=new Date(snapshot.date).toLocaleString();$('snapshot-inputs').innerHTML=table(['Parameter','Value'],labels.map((l,i)=>[l,fmt(snapshot.values[i],7)]));for(const [id,key] of [['plan-name','name'],['notes','notes'],['measured','measured'],['bandwidth','bandwidth'],['noiseFigure','noiseFigure'],['requiredSNR','requiredSNR']])$(id).value=snapshot[key]??'';drawChart();updateAnalysis();}
for(const [id,label,v,u] of [['bandwidth','Bandwidth','1000000','Hz'],['noiseFigure','Total system noise figure','3','dB'],['requiredSNR','Required SNR','10','dB']])$('noise-fields').insertAdjacentHTML('beforeend',field(id,label,v,u));
function syncMeta(){if(!snapshot)return;for(const [id,key] of [['plan-name','name'],['notes','notes'],['measured','measured'],['bandwidth','bandwidth'],['noiseFigure','noiseFigure'],['requiredSNR','requiredSNR']])snapshot[key]=$(id).value;}
function updateAnalysis(){if(!snapshot)return;syncMeta();const n=noise(snapshot.values,number(snapshot.bandwidth),number(snapshot.noiseFigure),number(snapshot.requiredSNR));$('noise-results').innerHTML=n?table(['Item','Result'],[['Input-referred noise',fmt(n.floor)+' dBm'],['Estimated SNR',fmt(n.snr)+' dB'],['SNR margin',fmt(n.margin)+' dB'],['Verdict',n.margin>=0?'SNR target met':'SNR target not met']]):'<p class="error">Enter a positive bandwidth, a non-negative NF and a finite required SNR.</p>';const m=number(snapshot.measured),delta=m-budget(snapshot.values).output;$('measurement').textContent=snapshot.measured.trim()===''?'No measured value entered yet':Number.isFinite(delta)?`Measured − predicted: ${fmt(delta)} dB. ${delta<0?'Measured is lower; this may include unmodeled losses or measurement differences.':'Measured meets or exceeds the prediction.'}`:'Enter a finite power within range.';}
['bandwidth','noiseFigure','requiredSNR','measured','plan-name','notes'].forEach(id=>$(id).oninput=updateAnalysis);
let chartRange;function drawChart(){const v=snapshot.values,r=budget(v),center=Math.log10(v[1]),target=r.maxDistance?Math.log10(r.maxDistance):center,lo=Math.max(-150,Math.min(center-1,target-.2)),hi=Math.min(150,Math.max(center+1,target+.2));chartRange=[lo,hi];const points=Array.from({length:81},(_,i)=>{const log=lo+(hi-lo)*i/80;return [log,powerAt(v,10**log)];}),ys=[...points.map(p=>p[1]),v[8],v[8]+v[9]];let ymin=Math.min(...ys),ymax=Math.max(...ys);const pad=Math.max(5,(ymax-ymin)*.1);ymin-=pad;ymax+=pad;const x=l=>70+(l-lo)/(hi-lo)*820,y=p=>270-(p-ymin)/(ymax-ymin)*230;let svg='<svg viewBox="0 0 930 330" role="img" aria-label="Received power versus distance, distance on a logarithmic scale"><title>Received power decreases with distance</title>';for(let i=0;i<5;i++){const p=ymin+(ymax-ymin)*i/4,l=lo+(hi-lo)*i/4;svg+=`<line class="grid" x1="70" x2="890" y1="${y(p)}" y2="${y(p)}"/><text x="60" y="${y(p)+5}" text-anchor="end">${fmt(p,0)}</text><text x="${x(l)}" y="295" text-anchor="middle">${fmt(10**l,3)}</text>`;}svg+=`<line x1="70" x2="890" y1="${y(v[8])}" y2="${y(v[8])}" stroke="var(--orange)" stroke-dasharray="5 5"/><line x1="70" x2="890" y1="${y(v[8]+v[9])}" y2="${y(v[8]+v[9])}" stroke="var(--green)" stroke-dasharray="9 5"/><polyline points="${points.map(p=>`${x(p[0])},${y(p[1])}`).join(' ')}" fill="none" stroke="var(--blue)" stroke-width="3"/><text x="70" y="22">Receiver input (dBm)</text><text x="480" y="325" text-anchor="middle">Distance (km, log scale)</text></svg>`;$('chart').innerHTML=svg;$('max-distance').textContent='Maximum distance '+fmt(r.maxDistance,5)+' km';$('distance-slider').min=lo;$('distance-slider').max=hi;$('distance-slider').value=center;inspectDistance();}
function inspectDistance(){if(!snapshot)return;const d=10**number($('distance-slider').value);$('distance-readout').textContent=`Distance ${fmt(d,6)} km → receiver input ${fmt(powerAt(snapshot.values,d))} dBm`;}$('distance-slider').oninput=inspectDistance;
$('save').onclick=()=>{if(!snapshot)return;syncMeta();const p=structuredClone(snapshot);p.id=crypto.randomUUID();p.name=p.name.trim()||'Untitled link';const next=[p,...plans];if(write('rf.plans',next)){plans=next;renderPlans();notice(`Saved "${p.name}"`);}};
function renderPlans(){$('count').textContent=plans.length;$('plan-list').innerHTML=plans.length?plans.map(p=>`<article><label class="plan-title"><input type="checkbox" data-select="${esc(p.id)}" ${selected.includes(p.id)?'checked':''}>${esc(p.name)}</label><p class="hint">${esc(new Date(p.date).toLocaleString())}</p><p>Receiver input ${fmt(budget(p.values).output)} dBm · margin ${fmt(budget(p.values).margin)} dB</p><div class="actions"><button data-load="${esc(p.id)}">Load Parameters</button><button data-view="${esc(p.id)}">Analyze / Export</button><button data-delete="${esc(p.id)}">Delete</button></div></article>`).join(''):'<article><h3>No saved plans yet</h3><p>Calculate a link first, then save a named plan from the analysis section.</p></article>';const pair=selected.map(id=>plans.find(p=>p.id===id)).filter(Boolean);$('comparison').innerHTML=pair.length===2?`<article><h3>Plan Comparison: A → B</h3>${table(['Parameter','A: '+pair[0].name,'B: '+pair[1].name],[...labels.map((l,i)=>[l,fmt(pair[0].values[i],7),fmt(pair[1].values[i],7)]),['Receiver input (dBm)',fmt(budget(pair[0].values).output),fmt(budget(pair[1].values).output)],['Link margin (dB)',fmt(budget(pair[0].values).margin),fmt(budget(pair[1].values).margin)]])}<p>Δ Receiver input (B − A): ${fmt(budget(pair[1].values).output-budget(pair[0].values).output)} dB<br>Δ Margin (B − A): ${fmt(budget(pair[1].values).margin-budget(pair[0].values).margin)} dB</p></article>`:'';}
$('plan-list').onchange=e=>{const id=e.target.dataset.select;if(!id)return;if(e.target.checked){if(selected.length>=2){e.target.checked=false;notice('Select at most two plans.');return;}selected.push(id);}else selected=selected.filter(x=>x!==id);renderPlans();};
$('plan-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.load??b.dataset.view??b.dataset.delete,p=plans.find(x=>x.id===id);if(!p)return;if(b.dataset.delete){if(!confirm(`Delete "${p.name}"?`))return;const next=plans.filter(x=>x.id!==id);if(write('rf.plans',next)){plans=next;selected=selected.filter(x=>x!==id);renderPlans();}return;}loaded=structuredClone(p);$('frequency-unit').value='1';$('distance-unit').value='1';resetF();resetD();p.values.forEach((v,i)=>$('v'+i).value=v);invalidate();tab('budget');if(b.dataset.view){snapshot=structuredClone(p);showSnapshot();$('analysis').scrollIntoView();}else notice('Parameters loaded. Press Calculate to update the results.');};
$('pdf').onclick=()=>{if(!snapshot)return;syncMeta();const p=snapshot,r=budget(p.values),n=noise(p.values,number(p.bandwidth),number(p.noiseFigure),number(p.requiredSNR));$('print-report').innerHTML=`<h1>LAB602 · RF Link Budget Report</h1><h2>${esc(p.name||'Untitled link')}</h2><p>${esc(new Date(p.date).toLocaleString())}</p><h2>Input Parameters</h2>${table(['Parameter','Value'],labels.map((l,i)=>[l,fmt(p.values[i],7)]))}<h2>Results</h2>${table(['Item','Result'],[['Verdict',r.status],['Receiver input',fmt(r.output)+' dBm'],['RX antenna output',fmt(r.received)+' dBm'],['FSPL',fmt(r.fspl)+' dB'],['Link margin',fmt(r.margin)+' dB'],['Maximum distance',fmt(r.maxDistance,7)+' km']])}<h2>Seven-Stage Power</h2>${table(['Stage','Calculation','Power (dBm)'],r.stages.map(([a,b,c])=>[a,b,fmt(c)]))}<h2>Noise and Measurement</h2>${table(['Item','Value'],[['Bandwidth (Hz)',p.bandwidth],['Total system NF (dB)',p.noiseFigure],['Required SNR (dB)',p.requiredSNR],['Input-referred noise (dBm)',n?fmt(n.floor):'Invalid input'],['Estimated SNR (dB)',n?fmt(n.snr):'Invalid input'],['SNR margin (dB)',n?fmt(n.margin):'Invalid input'],['Measured receiver input (dBm)',p.measured||'Not provided'],['Measured − predicted (dB)',p.measured?fmt(number(p.measured)-r.output):'Not provided']])}<h2>Experiment Notes</h2><p class="report-notes">${esc(p.notes)}</p><h2>Model Assumptions</h2><p>${esc(document.querySelector('.assumptions').textContent)}</p><p>Noise assumes 290 K. The total system NF includes the RX cable, amplifier and receiver, referred to the RX antenna output; the amplifier NF alone must not be used. Measurements are taken at the receiver input.</p>`;window.print();};
const prefs=read('rf.prefs',{});$('theme').value=['system','light','dark'].includes(prefs.theme)?prefs.theme:'system';$('animation').checked=prefs.animation!==false;$('haptics').checked=prefs.haptics===true;const media=matchMedia('(prefers-color-scheme: dark)');function theme(){document.body.dataset.theme=$('theme').value==='system'?(media.matches?'dark':'light'):$('theme').value;}theme();media.addEventListener('change',theme);['theme','animation','haptics'].forEach(id=>$(id).onchange=()=>{theme();write('rf.prefs',{theme:$('theme').value,animation:$('animation').checked,haptics:$('haptics').checked});});
const toolIds=['power-direction','power-input','doppler-frequency','doppler-frequency-unit','doppler-speed','doppler-speed-unit','motion'],toolSaved=read('rf.tools',{});for(const id of toolIds)if(typeof toolSaved[id]==='string')$(id).value=toolSaved[id];
function persistTools(){write('rf.tools',Object.fromEntries(toolIds.map(id=>[id,$(id).value])));}
function powerResult(){const w=$('power-direction').value==='watts',v=convertPower(number($('power-input').value),w);$('power-label').textContent=`Input power (${w?'dBm':'W'})`;$('power-result').innerHTML=`<p class="eyebrow">CONVERTED POWER</p><div class="big">${v===null?'— —':fmt(v,10)}</div><p>${w?'W':'dBm'}</p>${v===null?'<small>Enter a valid power; W must be greater than zero and the result must be finite.</small>':''}`;persistTools();}
$('power-input').oninput=powerResult;const powerInputs=read('rf.powerInputs',{watts:'',dbm:''});let previousPower=$('power-direction').value;$('power-input').addEventListener('input',()=>{powerInputs[$('power-direction').value]=$('power-input').value;write('rf.powerInputs',powerInputs);});$('power-direction').onchange=()=>{powerInputs[previousPower]=$('power-input').value;previousPower=$('power-direction').value;$('power-input').value=powerInputs[previousPower]??'';powerResult();};$('power-clear').onclick=()=>{$('power-input').value='';powerInputs[previousPower]='';write('rf.powerInputs',powerInputs);powerResult();};
function dopplerResult(){const speed=number($('doppler-speed').value),f=number($('doppler-frequency').value)*number($('doppler-frequency-unit').value),v=speed*number($('doppler-speed-unit').value)*number($('motion').value),r=speed>=0?doppler(f,v):null,u=$('doppler-frequency-unit').selectedOptions[0]?.textContent??'Hz';$('doppler-result').innerHTML=`<p class="eyebrow">FREQUENCY OFFSET</p><div class="big">${r?((r.shift>0?'+':'')+fmt(r.shift,9)):'— —'}</div><p>Hz ${r?'· '+fmt(r.shift/1000,9)+' kHz':''}</p>${r?`<hr><p>Received frequency</p><h2 class="mono">${fmt(r.received/number($('doppler-frequency-unit').value),12)} ${u}</h2><p>${r.shift===0?'No radial motion, no frequency shift.':r.shift>0?'Approaching: received frequency increases.':'Receding: received frequency decreases.'}</p>`:'<small>Enter a positive frequency and a non-negative radial velocity between 0 and 2,997.92458 km/s.</small>'}`;persistTools();}
bindUnit('doppler-frequency-unit','doppler-frequency',dopplerResult);bindUnit('doppler-speed-unit','doppler-speed',dopplerResult);['doppler-frequency','doppler-speed'].forEach(id=>$(id).oninput=dopplerResult);$('motion').onchange=dopplerResult;$('doppler-clear').onclick=()=>{$('doppler-frequency').value='';$('doppler-speed').value='';dopplerResult();};renderPlans();powerResult();dopplerResult();
