import {labels,number,budget,powerAt,noise,convertPower,doppler,validPlan} from './calculations.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=2)=>x==null||!Number.isFinite(x)?'超出範圍':(x!==0&&(Math.abs(x)<.001||Math.abs(x)>=1e9)?x.toExponential(6):x.toLocaleString('en-US',{maximumFractionDigits:d}));
let timer;function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('notice').hidden=true,5500);}
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function write(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true;}catch{notice('無法儲存：瀏覽器儲存空間已滿或未開放。');return false;}}
const names=['頻率','距離','TX 功率','TX 天線增益','RX 天線增益','RX 放大器增益','TX 線路損耗','RX 線路損耗','接收靈敏度','所需餘裕'];
const units=['MHz','km','dBm','dBi','dBi','dB','dB','dB','dBm','dB'],defaults=['','','','','','0','0','0','','0'],placeholder=['2.4','1','20','2','2','0','0','0','-90','10'];
function field(id,title,value,unit='',extra=''){return `<label for="${id}">${title}<div class="input-unit"><input id="${id}" inputmode="decimal" value="${esc(value)}" ${extra}>${unit?`<span>${unit}</span>`:''}</div></label>`;}
for(let i=0;i<10;i++){const parent=i<2?'propagation':i<5?'antenna':i<8?'losses':'requirements';$(parent).insertAdjacentHTML('beforeend',field('v'+i,names[i],defaults[i],i<2?'':units[i],`placeholder="例如 ${placeholder[i]}"`));}
$('v0').after(Object.assign(document.createElement('select'),{id:'frequency-unit',ariaLabel:'頻率單位',innerHTML:'<option value="1000">GHz</option><option value="1">MHz</option>'}));
$('v1').after(Object.assign(document.createElement('select'),{id:'distance-unit',ariaLabel:'距離單位',innerHTML:'<option value="1">km</option><option value="0.001">m</option>'}));
const saved=read('rf.inputs',{});for(const [id,v] of Object.entries(saved)){if($(id)&&typeof v==='string')$(id).value=v;}
const draftIds=[...Array.from({length:10},(_,i)=>'v'+i),'frequency-unit','distance-unit'];
function persist(){write('rf.inputs',Object.fromEntries(draftIds.map(id=>[id,$(id).value])));}
let snapshot=null,loaded=null,undo=null,plans=read('rf.plans',[]),selected=[];plans=Array.isArray(plans)?plans.filter(validPlan):[];
function tab(id){document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-tab]').forEach(e=>{if(e.dataset.tab===id)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current');});if(id==='plans')renderPlans();}
document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>tab(e.dataset.tab));
function invalidate(){snapshot=null;$('analysis').hidden=true;$('breakdown').hidden=true;$('error').textContent='';$('result').innerHTML='<p class="eyebrow">LINK PERFORMANCE</p><h2>等待計算</h2><p>參數已更新，請按下「計算鏈路預算」。</p>';persist();}
for(let i=0;i<10;i++)$('v'+i).addEventListener('input',invalidate);
function bindUnit(selectId,inputId,onChange){const el=$(selectId);let old=number(el.value);el.addEventListener('change',()=>{const value=number($(inputId).value),next=number(el.value);if(Number.isFinite(value)){const converted=value*(old/next);$(inputId).value=Number.isFinite(converted)&&!(value!==0&&converted===0)?String(Number(converted.toPrecision(15))):'';}old=next;onChange();});return ()=>old=number(el.value);}
const resetF=bindUnit('frequency-unit','v0',invalidate),resetD=bindUnit('distance-unit','v1',invalidate);
function values(){return Array.from({length:10},(_,i)=>number($('v'+i).value)*(i===0?number($('frequency-unit').value):i===1?number($('distance-unit').value):1));}
$('budget-form').onsubmit=e=>{e.preventDefault();try{const v=values();budget(v);snapshot={...(loaded??{}),id:crypto.randomUUID(),date:new Date().toISOString(),values:v,name:loaded?.name??'',notes:loaded?.notes??'',bandwidth:loaded?.bandwidth??'1000000',noiseFigure:loaded?.noiseFigure??'3',requiredSNR:loaded?.requiredSNR??'10',measured:loaded?.measured??''};$('error').textContent='';showSnapshot();if($('animation').checked&&!matchMedia('(prefers-reduced-motion: reduce)').matches){$('result').classList.remove('pulse');void $('result').offsetWidth;$('result').classList.add('pulse');}if($('haptics').checked&&navigator.vibrate)navigator.vibrate(30);}catch(err){$('error').textContent=err.message;const i=values().findIndex((v,i)=>!Number.isFinite(v)||(i<2&&v<=0)||([6,7,9].includes(i)&&v<0));if(i>=0){const el=$('v'+i),detail=el.closest('details');if(detail)detail.open=true;el.focus();}}};
$('clear').onclick=()=>{undo={fields:Object.fromEntries(draftIds.map(id=>[id,$(id).value])),loaded};for(let i=0;i<10;i++)$('v'+i).value=defaults[i];loaded=null;invalidate();$('undo').hidden=false;};
$('undo').onclick=()=>{if(!undo)return;for(const [id,v] of Object.entries(undo.fields))$(id).value=v;loaded=undo.loaded;resetF();resetD();undo=null;$('undo').hidden=true;invalidate();};
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function showSnapshot(){const r=budget(snapshot.values);$('result').innerHTML=`<p class="eyebrow">LINK PERFORMANCE</p><p class="status ${r.meets?'':'warn'}">${r.status}</p><p>鏈路餘裕</p><div class="big">${fmt(r.margin)} <small>dB</small></div><small>所需餘裕 ${fmt(snapshot.values[9])} dB</small><div class="metrics">${[['接收器輸入',r.output,'dBm'],['RX 天線輸出',r.received,'dBm'],['自由空間損耗',r.fspl,'dB'],['最大距離',r.maxDistance,'km']].map(([l,v,u])=>`<div><small>${l}</small><strong>${fmt(v)} ${u}</strong></div>`).join('')}</div>`;$('breakdown').hidden=false;$('breakdown').innerHTML='<h3>七階段功率分析</h3>'+r.stages.map(([n,o,p],i)=>`<div class="stage"><div>${i+1}. ${n}<small>${esc(o)}</small></div><b>${fmt(p)} dBm</b></div>`).join('');$('analysis').hidden=false;$('calculated-at').textContent=new Date(snapshot.date).toLocaleString();$('snapshot-inputs').innerHTML=table(['參數','數值'],labels.map((l,i)=>[l,fmt(snapshot.values[i],7)]));for(const [id,key] of [['plan-name','name'],['notes','notes'],['measured','measured'],['bandwidth','bandwidth'],['noiseFigure','noiseFigure'],['requiredSNR','requiredSNR']])$(id).value=snapshot[key]??'';drawChart();updateAnalysis();}
for(const [id,label,v,u] of [['bandwidth','頻寬','1000000','Hz'],['noiseFigure','總系統雜訊指數','3','dB'],['requiredSNR','所需 SNR','10','dB']])$('noise-fields').insertAdjacentHTML('beforeend',field(id,label,v,u));
function syncMeta(){if(!snapshot)return;for(const [id,key] of [['plan-name','name'],['notes','notes'],['measured','measured'],['bandwidth','bandwidth'],['noiseFigure','noiseFigure'],['requiredSNR','requiredSNR']])snapshot[key]=$(id).value;}
function updateAnalysis(){if(!snapshot)return;syncMeta();const n=noise(snapshot.values,number(snapshot.bandwidth),number(snapshot.noiseFigure),number(snapshot.requiredSNR));$('noise-results').innerHTML=n?table(['項目','結果'],[['輸入參考雜訊',fmt(n.floor)+' dBm'],['估計 SNR',fmt(n.snr)+' dB'],['SNR 餘裕',fmt(n.margin)+' dB'],['判定',n.margin>=0?'達到 SNR 目標':'未達 SNR 目標']]):'<p class="error">請輸入正頻寬、非負 NF 與有限的所需 SNR。</p>';const m=number(snapshot.measured),delta=m-budget(snapshot.values).output;$('measurement').textContent=snapshot.measured.trim()===''?'尚未輸入實測值':Number.isFinite(delta)?`實測 − 預測：${fmt(delta)} dB。${delta<0?'實測較低，可能包含未建模損耗或量測差異。':'實測達到或高於預測。'}`:'請輸入範圍內的有限功率。';}
['bandwidth','noiseFigure','requiredSNR','measured','plan-name','notes'].forEach(id=>$(id).oninput=updateAnalysis);
let chartRange;function drawChart(){const v=snapshot.values,r=budget(v),center=Math.log10(v[1]),target=r.maxDistance?Math.log10(r.maxDistance):center,lo=Math.max(-150,Math.min(center-1,target-.2)),hi=Math.min(150,Math.max(center+1,target+.2));chartRange=[lo,hi];const points=Array.from({length:81},(_,i)=>{const log=lo+(hi-lo)*i/80;return [log,powerAt(v,10**log)];}),ys=[...points.map(p=>p[1]),v[8],v[8]+v[9]];let ymin=Math.min(...ys),ymax=Math.max(...ys);const pad=Math.max(5,(ymax-ymin)*.1);ymin-=pad;ymax+=pad;const x=l=>70+(l-lo)/(hi-lo)*820,y=p=>270-(p-ymin)/(ymax-ymin)*230;let svg='<svg viewBox="0 0 930 330" role="img" aria-label="接收功率與距離圖，距離使用對數刻度"><title>接收功率隨距離增加而降低</title>';for(let i=0;i<5;i++){const p=ymin+(ymax-ymin)*i/4,l=lo+(hi-lo)*i/4;svg+=`<line class="grid" x1="70" x2="890" y1="${y(p)}" y2="${y(p)}"/><text x="60" y="${y(p)+5}" text-anchor="end">${fmt(p,0)}</text><text x="${x(l)}" y="295" text-anchor="middle">${fmt(10**l,3)}</text>`;}svg+=`<line x1="70" x2="890" y1="${y(v[8])}" y2="${y(v[8])}" stroke="var(--orange)" stroke-dasharray="5 5"/><line x1="70" x2="890" y1="${y(v[8]+v[9])}" y2="${y(v[8]+v[9])}" stroke="var(--green)" stroke-dasharray="9 5"/><polyline points="${points.map(p=>`${x(p[0])},${y(p[1])}`).join(' ')}" fill="none" stroke="var(--blue)" stroke-width="3"/><text x="70" y="22">接收器輸入 (dBm)</text><text x="480" y="325" text-anchor="middle">距離 (km，對數刻度)</text></svg>`;$('chart').innerHTML=svg;$('max-distance').textContent='最大距離 '+fmt(r.maxDistance,5)+' km';$('distance-slider').min=lo;$('distance-slider').max=hi;$('distance-slider').value=center;inspectDistance();}
function inspectDistance(){if(!snapshot)return;const d=10**number($('distance-slider').value);$('distance-readout').textContent=`距離 ${fmt(d,6)} km → 接收器輸入 ${fmt(powerAt(snapshot.values,d))} dBm`;}$('distance-slider').oninput=inspectDistance;
$('save').onclick=()=>{if(!snapshot)return;syncMeta();const p=structuredClone(snapshot);p.id=crypto.randomUUID();p.name=p.name.trim()||'未命名鏈路';const next=[p,...plans];if(write('rf.plans',next)){plans=next;renderPlans();notice(`已儲存「${p.name}」`);}};
function renderPlans(){$('count').textContent=plans.length;$('plan-list').innerHTML=plans.length?plans.map(p=>`<article><label class="plan-title"><input type="checkbox" data-select="${esc(p.id)}" ${selected.includes(p.id)?'checked':''}>${esc(p.name)}</label><p class="hint">${esc(new Date(p.date).toLocaleString())}</p><p>接收器輸入 ${fmt(budget(p.values).output)} dBm · 餘裕 ${fmt(budget(p.values).margin)} dB</p><div class="actions"><button data-load="${esc(p.id)}">載入參數</button><button data-view="${esc(p.id)}">分析／匯出</button><button data-delete="${esc(p.id)}">刪除</button></div></article>`).join(''):'<article><h3>尚未儲存方案</h3><p>先計算鏈路，再於分析區儲存具名方案。</p></article>';const pair=selected.map(id=>plans.find(p=>p.id===id)).filter(Boolean);$('comparison').innerHTML=pair.length===2?`<article><h3>方案比較：A → B</h3>${table(['參數','A：'+pair[0].name,'B：'+pair[1].name],[...labels.map((l,i)=>[l,fmt(pair[0].values[i],7),fmt(pair[1].values[i],7)]),['接收器輸入 (dBm)',fmt(budget(pair[0].values).output),fmt(budget(pair[1].values).output)],['鏈路餘裕 (dB)',fmt(budget(pair[0].values).margin),fmt(budget(pair[1].values).margin)]])}<p>Δ 接收器輸入 (B − A)：${fmt(budget(pair[1].values).output-budget(pair[0].values).output)} dB<br>Δ 餘裕 (B − A)：${fmt(budget(pair[1].values).margin-budget(pair[0].values).margin)} dB</p></article>`:'';}
$('plan-list').onchange=e=>{const id=e.target.dataset.select;if(!id)return;if(e.target.checked){if(selected.length>=2){e.target.checked=false;notice('最多選擇兩個方案。');return;}selected.push(id);}else selected=selected.filter(x=>x!==id);renderPlans();};
$('plan-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.load??b.dataset.view??b.dataset.delete,p=plans.find(x=>x.id===id);if(!p)return;if(b.dataset.delete){if(!confirm(`刪除「${p.name}」？`))return;const next=plans.filter(x=>x.id!==id);if(write('rf.plans',next)){plans=next;selected=selected.filter(x=>x!==id);renderPlans();}return;}loaded=structuredClone(p);$('frequency-unit').value='1';$('distance-unit').value='1';resetF();resetD();p.values.forEach((v,i)=>$('v'+i).value=v);invalidate();tab('budget');if(b.dataset.view){snapshot=structuredClone(p);showSnapshot();$('analysis').scrollIntoView();}else notice('已載入參數，按下計算以更新結果。');};
$('pdf').onclick=()=>{if(!snapshot)return;syncMeta();const p=snapshot,r=budget(p.values),n=noise(p.values,number(p.bandwidth),number(p.noiseFigure),number(p.requiredSNR));$('print-report').innerHTML=`<h1>LAB602 · RF Link Budget Report</h1><h2>${esc(p.name||'未命名鏈路')}</h2><p>${esc(new Date(p.date).toLocaleString())}</p><h2>輸入參數</h2>${table(['參數','數值'],labels.map((l,i)=>[l,fmt(p.values[i],7)]))}<h2>計算結果</h2>${table(['項目','結果'],[['判定',r.status],['接收器輸入',fmt(r.output)+' dBm'],['RX 天線輸出',fmt(r.received)+' dBm'],['FSPL',fmt(r.fspl)+' dB'],['鏈路餘裕',fmt(r.margin)+' dB'],['最大距離',fmt(r.maxDistance,7)+' km']])}<h2>七階段功率</h2>${table(['階段','計算','功率 (dBm)'],r.stages.map(([a,b,c])=>[a,b,fmt(c)]))}<h2>雜訊與實測</h2>${table(['項目','數值'],[['頻寬 (Hz)',p.bandwidth],['總系統 NF (dB)',p.noiseFigure],['所需 SNR (dB)',p.requiredSNR],['輸入參考雜訊 (dBm)',n?fmt(n.floor):'無效輸入'],['估計 SNR (dB)',n?fmt(n.snr):'無效輸入'],['SNR 餘裕 (dB)',n?fmt(n.margin):'無效輸入'],['實測接收器輸入 (dBm)',p.measured||'未提供'],['實測 − 預測 (dB)',p.measured?fmt(number(p.measured)-r.output):'未提供']])}<h2>實驗備註</h2><p class="report-notes">${esc(p.notes)}</p><h2>模型假設</h2><p>${esc(document.querySelector('.assumptions').textContent)}</p><p>雜訊假設 290 K。總系統 NF 包含 RX 線纜、放大器與接收器，參考至 RX 天線輸出；不可僅使用放大器 NF。實測位置為接收器輸入。</p>`;window.print();};
const prefs=read('rf.prefs',{});$('theme').value=['system','light','dark'].includes(prefs.theme)?prefs.theme:'system';$('animation').checked=prefs.animation!==false;$('haptics').checked=prefs.haptics===true;const media=matchMedia('(prefers-color-scheme: dark)');function theme(){document.body.dataset.theme=$('theme').value==='system'?(media.matches?'dark':'light'):$('theme').value;}theme();media.addEventListener('change',theme);['theme','animation','haptics'].forEach(id=>$(id).onchange=()=>{theme();write('rf.prefs',{theme:$('theme').value,animation:$('animation').checked,haptics:$('haptics').checked});});
const toolIds=['power-direction','power-input','doppler-frequency','doppler-frequency-unit','doppler-speed','doppler-speed-unit','motion'],toolSaved=read('rf.tools',{});for(const id of toolIds)if(typeof toolSaved[id]==='string')$(id).value=toolSaved[id];
function persistTools(){write('rf.tools',Object.fromEntries(toolIds.map(id=>[id,$(id).value])));}
function powerResult(){const w=$('power-direction').value==='watts',v=convertPower(number($('power-input').value),w);$('power-label').textContent=`輸入功率 (${w?'dBm':'W'})`;$('power-result').innerHTML=`<p class="eyebrow">CONVERTED POWER</p><div class="big">${v===null?'— —':fmt(v,10)}</div><p>${w?'W':'dBm'}</p>${v===null?'<small>請輸入有效功率；W 必須大於零，結果須在有限範圍內。</small>':''}`;persistTools();}
$('power-input').oninput=powerResult;const powerInputs=read('rf.powerInputs',{watts:'',dbm:''});let previousPower=$('power-direction').value;$('power-input').addEventListener('input',()=>{powerInputs[$('power-direction').value]=$('power-input').value;write('rf.powerInputs',powerInputs);});$('power-direction').onchange=()=>{powerInputs[previousPower]=$('power-input').value;previousPower=$('power-direction').value;$('power-input').value=powerInputs[previousPower]??'';powerResult();};$('power-clear').onclick=()=>{$('power-input').value='';powerInputs[previousPower]='';write('rf.powerInputs',powerInputs);powerResult();};
function dopplerResult(){const speed=number($('doppler-speed').value),f=number($('doppler-frequency').value)*number($('doppler-frequency-unit').value),v=speed*number($('doppler-speed-unit').value)*number($('motion').value),r=speed>=0?doppler(f,v):null,u=$('doppler-frequency-unit').selectedOptions[0]?.textContent??'Hz';$('doppler-result').innerHTML=`<p class="eyebrow">FREQUENCY OFFSET</p><div class="big">${r?((r.shift>0?'+':'')+fmt(r.shift,9)):'— —'}</div><p>Hz ${r?'· '+fmt(r.shift/1000,9)+' kHz':''}</p>${r?`<hr><p>接收頻率</p><h2 class="mono">${fmt(r.received/number($('doppler-frequency-unit').value),12)} ${u}</h2><p>${r.shift===0?'無徑向運動，無頻移。':r.shift>0?'靠近：接收頻率增加。':'遠離：接收頻率降低。'}</p>`:'<small>請輸入正頻率與 0 至 2,997.92458 km/s 的非負徑向速度。</small>'}`;persistTools();}
bindUnit('doppler-frequency-unit','doppler-frequency',dopplerResult);bindUnit('doppler-speed-unit','doppler-speed',dopplerResult);['doppler-frequency','doppler-speed'].forEach(id=>$(id).oninput=dopplerResult);$('motion').onchange=dopplerResult;$('doppler-clear').onclick=()=>{$('doppler-frequency').value='';$('doppler-speed').value='';dopplerResult();};renderPlans();powerResult();dopplerResult();
